/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: germydan (https://sketchfab.com/germydan)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/mew-pokemon-4c9dfbb590744368a05f1bed1fbf8d3e
title: Mew Pokémon
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/space/mew.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-32.25, -63.75, -29.64]}>
          <mesh
            geometry={nodes.Object_2.geometry}
            material={materials.wire_228153184}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/mew.gltf");
